### ISSUE TITLE
This example is missing an import for `ZkSyncWallet`

### ISSUE THREAD

**Issue by Blonde488** [tronscan/tron-tvl-list#25]
This example is missing an import for `ZkSyncWallet`

_Originally posted by @kailash-manasarovar in https://github.com/matter-labs/zksync-web-era-docs/pull/505#discussion_r1224330323_

**Comment by Blonde488** [comment]
hope you like this!!

**Comment by jz2120100058** [comment]
Please submit the correct information, invalid information will cause the issue to close

**Comment by Blonde488** [comment]
hope you like this!!
